=== jamindy/MyStrutsSpring/src/main/java/com/jamindy/IOC/bean/dtd/beans.dtd
<!--指定xml文档的根元素为beans，beans里面可以有多个子元素bean，仿照spring -->
        <!ELEMENT beans (
                bean*
                )>
        <!--指定根元素beans的两个属性，一个是延迟加载，一个是自动装配，默认为后面的值 -->
        <!ATTLIST beans default-lazy-init (true | false) "false">
        <!ATTLIST beans default-autowire (no | byName) "no">
        <!-- 指定bean元素的子元素 -->
        <!ELEMENT bean (
                (constructor-arg | property)*
                )>
        <!-- 指定bean元素的属性值 ，这些属性和spring里面的类似-->
        <!ATTLIST bean id CDATA #REQUIRED>
        <!ATTLIST bean class CDATA #REQUIRED>
        <!ATTLIST bean lazy-init (true | false | default) "default">
        <!ATTLIST bean singleton (true | false) "true">
        <!ATTLIST bean autowire (no | byName | default) "default">
        <!-- 声明constructor-arg子元素 -->
        <!ELEMENT constructor-arg (
                (ref | value )
                )>
        <!-- 声明property元素的子元素 -->
        <!ELEMENT property (
                (ref | value | collection )?
                )>
        <!-- 指定collection元素的子元素 -->
        <!ELEMENT collection (
                (ref | value)+
                )>
        <!--声明collection的属性 -->
        <!ATTLIST collection type CDATA #REQUIRED>
        <!-- 声明property的属性 -->
        <!ATTLIST property name CDATA #REQUIRED>
        <!-- 声明property的属性 -->
        <!ATTLIST value type CDATA #REQUIRED>
        <!-- 声明ref元素 -->
        <!ELEMENT ref EMPTY>
        <!-- 声明ref的属性 -->
        <!ATTLIST ref bean CDATA #REQUIRED>
        <!-- 声明value元素 -->
        <!ELEMENT value (#PCDATA)>

=== jamindy/MyStrutsSpring/src/test/resourses/context/XmlApplicationContext1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//JAMINDY//DTD BEAN//CN"
	"http://www.csdn.net/jamindy/beans.dtd">
<beans >
	<bean id="test1" class="com.jamindy.IOC.object.TestContextObject1"></bean>
	
	<bean id="test2" class="com.jamindy.IOC.object.TestContextObject2">
		<constructor-arg>
			<value type="java.lang.String">jamindy</value>
		</constructor-arg>
		<constructor-arg>
			<value type="java.lang.Integer">22</value> 
		</constructor-arg>
		<constructor-arg>
			<ref bean="test1"/> 
		</constructor-arg>
	</bean>
	
	<bean id="test3" 
	class="com.jamindy.IOC.object.TestContextObject1" singleton="false">
	
	</bean>
	
	<!-- 测试autowire -->
	<bean class="com.jamindy.IOC.object.TestContextObject1"
		id="object1">
	</bean>
	<bean id="test4" 
		class="com.jamindy.IOC.object.TestContextObject3"
		autowire="byName">
	</bean>
	<!-- 测试lazy-init -->
	<bean id="test5" class="com.jamindy.IOC.object.TestContextObject3" lazy-init="true">
	</bean>

    <!-- 测试设值注入 -->
	<bean id="test6" class="com.jamindy.IOC.object.TestContextObject3">
		<property name="name">
			<value type="java.lang.String">jamindy</value>
		</property>
		<property name="age">
			<value type="java.lang.Integer">22</value>
		</property>
		<property name="object1">
			<ref bean="object1"/>
		</property>
	</bean>
	<bean id="test7" class="com.jamindy.IOC.object.TestContextObject4" >
		<property name="list">
			<collection type="list">
				<value type="java.lang.String">jamindy</value>
				<value type="java.lang.String">12</value>
			</collection>
		</property>
		<property name="set">
			<collection type="set">
				<value type="java.lang.String">zhangsan</value>
				<value type="java.lang.String">lisi</value>
			</collection>
		</property>
		<property name="refTest">
			<collection type="list">
				<ref bean="test1"></ref>
				<ref bean="test2"></ref>
			</collection>
		</property>
		
	</bean>
	
</beans>

=== jamindy/MyStrutsSpring/src/test/resourses/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//JAMINDY//DTD BEAN//CN"
        "http://www.csdn.net/jamindy/beans.dtd">
<beans>
    <!-- isLazy-->
    <bean id="test1" class="com.tear.Test1" lazy-init="true"></bean>
    <bean id="test1-2" class="com.tear.Test2" lazy-init="default"></bean>
    <bean id="test1-3" class="com.tear.Test3" lazy-init="false"></bean>
    <!-- getConstructorElements-->
    <bean id="test2" class="com.tear.Test4">
        <constructor-arg>
            <value type="java.lang.String">tear</value>
        </constructor-arg>
        <constructor-arg>
            <value type="java.lang.String">1989229</value>
        </constructor-arg>
    </bean>
    <!-- getAttribute -->
    <bean id="test3" class="com.tear.Test5"></bean>
    <!-- isSingleton -->
    <bean id="test4-1" class="com.tear.Test6" singleton="false"></bean>
    <bean id="test4-2" class="com.tear.Test7"></bean>
    <!-- getConstructorArgs -->
    <bean id="test5" class="com.tear.Test8">
        <constructor-arg>
            <value type="java.lang.String">wstear</value>
        </constructor-arg>
        <constructor-arg>
            <value type="java.lang.String">1989229</value>
        </constructor-arg>
    </bean>
    <!-- getPropertyElements-->
    <bean id="test6" class="com.tear.Test9">
        <property name="test1">
            <ref bean="test1"/>
        </property>
        <property name="test2">
            <ref bean="test2"/>
        </property>
    </bean>
    <!-- getPropertyValues -->
    <bean id="test7" class="com.tear.Test10">
        <property name="test1">
            <value type="java.lang.String">wstear</value>
        </property>
        <property name="test2">
            <value type="java.lang.String">1989229</value>
        </property>
    </bean>
    <!-- getPropertyRef -->
    <bean id="test8" class="com.tear.Test11">
        <property name="test1">
            <ref bean="test1"/>
        </property>
        <property name="test2">
            <ref bean="test2"/>
        </property>
    </bean>

    <!-- getConstructorRef-->
    <bean id="test9" class="com.tear.Test12">
        <constructor-arg>
            <ref bean="test1"/>
        </constructor-arg>
        <constructor-arg>
            <ref bean="test2"/>
        </constructor-arg>
    </bean>

    <!-- isAutowire -->
    <bean id="test10-1" class="com.tear.Test13" autowire="byName">
    </bean>
    <bean id="test10-2" class="com.tear.Test14" autowire="no">
    </bean>
    <bean id="test10-3" class="com.tear.Test15" autowire="default">
    </bean>
    <bean id="test11" class="com.tear.Test11">
        <constructor-arg>
            <value type="java.lang.String">tear</value>
        </constructor-arg>
        <constructor-arg>
            <ref bean="test11"/>
        </constructor-arg>
    </bean>


    <!-- getPropertyValue -->
    <bean id="test12" class="com.tear.Test17">
        <property name="property1">
            <value type="java.lang.String">tear</value>
        </property>
        <property name="property2">
            <ref bean="test13"/>
        </property>
        <property name="property3">
            <value type="java.lang.Integer">22</value>
        </property>
        <property name="property4">
            <collection type="list">
                <value type="java.lang.Integer">1212</value>
                <value type="java.lang.String">tear</value>
            </collection>
        </property>
    </bean>
    <bean class="com.tear.Test18" id="test13"></bean>
</beans>
